### PR TITLE
Syntax highlight update

### PR DESCRIPTION
**Pull request by Gim3l**
Here is my attempt to address missing keywords and patterns for VSCode syntax highlighting.

### Todo

Highlight the following keywords:
- [x] Highlight the names of nodes, walkers, and graphs
- [x] Assignment, increment and decrement operators (=, +=, -=, ++, --) 
- [ ] Variable properties 
- [x] Function and method calls
- [ ] Node names under walkers
- [x] Keywords
     - [x] has
     - [x] can
     - [x] type
     - [x] strict
     - [x] ignore
     - [x] spawn
     - [x] with
     - [x] entry
     - [x] exit
     - [x] length
     - [x] keys
     - [x] context
     - [x]  info
     - [x] details
     - [x] import
     - [x] report
     - [x] digraph
     - [x] subgraph
     - [x] and
     - [x] or
     - [x] not
     - [x] activity
     - [x] assert

### CODE REVIEW

**Comment by marsninja** [comment]
Nice first contribution @Gim3l !! It looks good to me (LGTM) as a merge candidate. Did you want to merge or discuss first?

**Comment by Gim3l** [comment]
> Nice first contribution @Gim3l !! It looks good to me (LGTM) as a merge candidate. Did you want to merge or discuss first?

Yes, let's hold it for now.

**Comment by Gim3l** [comment]
@marsninja Can you please check this out?

**Comment by marsninja** [comment]
@Gim3l You good to merge, this LGTM as a next version.

**Comment by Gim3l** [comment]
> @Gim3l You good to merge? This LGTM as a next version.

Ok, great! You can go ahead and merge.

**Comment by marsninja** [comment]
Congrats on your first contribution @Gim3l

**Pull request merged**
