### PR TITLE
Add Url functionalities

### PR DESCRIPTION
**Pull request by apatel66**
Added some url functions to the standard library (is_valid, ping, download_text, and download_b64). Created associated tests as well.
Closes: https://github.com/Jaseci-Labs/jaseci/issues/665.

### CODE REVIEW

**Comment by apatel66** [comment]
Some of the GItHub unit tests were failing because of a ModuleNotForund error with the "validators" library. I added it to the setup.py file, but I'm not sure if that's the only place that needs to be updated.

**Comment by marsninja** [comment]
Cool, Thanks @apatel66 If this passes we'll merge. Thanks for the contribution!

Also ping me if you'd like to continue contributing!! Nice work!

**Review by marsninja — APPROVED** [review]
LGTM @apatel66

**Review by marsninja — APPROVED** [review]
LGTM!

**Pull request merged**
