### PR TITLE
Vscode graph visualizer

### PR DESCRIPTION
**Pull request by Gim3l**
Add "View Graph" command to preview visualize DOT files.

### Testing
1. Go to the debugger
2. Start the "Run Jac Extension" configuration
3. Open a Dot file in the extension host
4. Run the view graph command (SHIFT + CTRL/CMD + V)

### CODE REVIEW

**Review by marsninja — CHANGES_REQUESTED** [review]
Guess this isnt push ready, 1.5m new lines and 4k files seems odd. Let chat about it tomorrow.

**Comment by marsninja** [comment]
Hi @Gim3l , Any update on this?

**Comment by Gim3l** [comment]
> 

I'll fix this now, sorry.

**Review by marsninja — APPROVED** [review]
LGTM

**Pull request merged**
