### PR TITLE
rename requirements file, fix typos

### PR DESCRIPTION
**Pull request by pathakshyam**
rename requirements file, added serv_actions and change test url to reduce test time. Fixed typos

### CODE REVIEW

**Comment by marsninja** [comment]
@pathakshyam Dont forget to sing the CLA real quick.

**Comment by ypkang** [comment]
@pathakshyam Shawn and I made some updates to the PDF extractor on Thursday which caused some conflicts with this PR. Could you resolve this?

**Comment by ypkang** [comment]
I will resolve the conflicts here.

**Comment by ypkang** [comment]
@pathakshyam can you sign the contributor CLA real quick? I will handle the merge conflicts but I need you to sign the CLA.

**Comment by ypkang** [comment]
@pathakshyam thanks for signing the CLA Shyam. I have resolved the conflicts.

**Review by ypkang — APPROVED** [review]

**Pull request merged**
