### PR TITLE
[DO NOT MERGE]: Simple docs for Multipart, Walker Callback, Global Reference Syntax, Report

### PR DESCRIPTION
**Pull request by amadolid**

### CODE REVIEW

**Review by asimsalim — APPROVED** [review]
@marsninja @ypkang

**Comment by asimsalim** [comment]
@amadolid  Can you remove the WIP tag from this PR  ?

**Comment by marsninja** [comment]
@ypkang @amadolid @king-mango CAn you guys work together to move this over to some section of the actual Jaseci Docs (as opposed to jsserv readme. This is important to file in the official docs somewhere.

**Comment by ypkang** [comment]
@marsninja sure thing.

@amadolid Can you copy the markdown file to under https://github.com/Jaseci-Labs/jaseci/tree/main/docs/docs/Developing_with_JAC/?

@king-mango Once @amadolid has done that, can you make the necessary changes to have this be visible in docs site?

**Comment by king-mango** [comment]
@ypkang sure !

**Pull request closed without merging**
