### PR TITLE
[WIP] [UI Kit] Add todo-list example

### PR DESCRIPTION
**Pull request by Gim3l**
## Describe your changes
- [ ] Simplify process for rendering a page
- [ ] Implement todo page
- [ ] Run CRUD operations from the todo page
    - [ ] Add todo
    - [ ] List todos
    - [ ] Delete todo
    - [ ] Update todo

### CODE REVIEW

**Review by marsninja — COMMENTED** [review]
Can probably add this file to gitignore: jaseci_ui_kit/examples/todo-list/main.jir

**Comment by marsninja** [comment]
@Gim3l Is this ready? If its a work in progress add [WIP] in the pr title, and you can throw a checklist in the description of the various items you'd like to do before the merge, (also note that this particular PR includes both the graph viewer and todo-list example changes, this is fine, we can take them both in one commit but I think it deprecates the other PR, let me know if I might have missed something)

**Comment by Gim3l** [comment]
> @Gim3l Is this ready? If its a work in progress add [WIP] in the pr title, and you can throw a checklist in the description of the various items you'd like to do before the merge, (also note that this particular PR includes both the graph viewer and todo-list example changes, this is fine, we can take them both in one commit but I think it deprecates the other PR, let me know if I might have missed something)

Yes, I'm still working on it. I updated the title and description

**Comment by ypkang** [comment]
@Gim3l Is this PR still useful? If so, could you update it and we can get it merged. If not, feel free to close it. Trying to do a spring cleaning of our PRs :)

**Pull request closed without merging**
