### PR TITLE
[MULTIPART-FEATURE]: Allow multipart feature to support file uploading

### PR DESCRIPTION
**Pull request by amadolid**
## Describe your changes
CHANGES:
 - support multipart/form-data content type
 - Refactor _context to have specific holder on walker instance
 - _context will now be walker's attribute `request_context`
 - existing api can be coverted to multipart-form by just adding required fields such as nd, snt, ctx and name
 - ctx can be json file or json string (automatically parsed in backend)
 - additional non file fields will be included on walker.request_context.body
 - user can now add file type fields
 - files (excluding ctx field) will now be accessible on walker.request_context.body.theirFieldName
 - files type fields will now be converted to json serialable structure {name:, base64:, content-type:}

## Link to related issue
NA

## Does this introduce new feature or change existing feature of Jaseci? If so, please add tests.
New feature, to be added

## Will this impact Jaseci users? If so, please write a paragraph describing the impact.
User can now upload files without using base64. All of existing api can be converted to multipart/form-data
request metadata can now be access on walker's attribute `request_context`
will add additional jaseci syntax to support access of this attribute

## Anything in this PR should the Jaseci developer/contributor community pay particular attention to? If so, please describe.
All API that run walker will be affected tho it should work fine as before

### CODE REVIEW

**Comment by amadolid** [comment]
# Sample Request
image

# request_context
image

**Review by marsninja — COMMENTED** [review]
Excellent start! Lets hop on a call and disucss the other pieces to the implementation @amadolid

**Comment by amadolid** [comment]
## Sample Code
```
global a = "test";

walker sample {
    with entry {
        report global.a;
        report global.b;
        report global.context;
        report global.info;
        report global.info['request_context'];
    }
}
```

### Sample Request Payload
```
{
	"sample": "sample"
}
```

## Response
```
{
	"success": false,
	"report": [
		"test",
		null,
		{
			"a": "test"
		},
		{
			"request_context": {
				"method": "POST",
				"headers": {
					"Content-Length": "23",
					"Content-Type": "application/json",
					"Host": "localhost:8000",
					"User-Agent": "insomnia/2022.3.0",
					"Cookie": "sessionid=nih6jwstnmv98nybhltx4bdq8xfmk1nv; csrftoken=NRE0oJztYc1lXjvpe7LSQxKQBI9I06VshSBkpxHnYF2HU1h1G52cXkjKFsQcuDUS",
					"Accept": "*/*"
				},
				"query": {
					"key": "97ca941e6bf1f43c3a4e531e40b2ad5a"
				},
				"body": {
					"sample": "sample"
				}
			}
		},
		{
			"method": "POST",
			"headers": {
				"Content-Length": "23",
				"Content-Type": "application/json",
				"Host": "localhost:8000",
				"User-Agent": "insomnia/2022.3.0",
				"Cookie": "sessionid=nih6jwstnmv98nybhltx4bdq8xfmk1nv; csrftoken=NRE0oJztYc1lXjvpe7LSQxKQBI9I06VshSBkpxHnYF2HU1h1G52cXkjKFsQcuDUS",
				"Accept": "*/*"
			},
			"query": {
				"key": "97ca941e6bf1f43c3a4e531e40b2ad5a"
			},
			"body": {
				"sample": "sample"
			}
		}
	],
	"errors": [
		"zsb:smooch_callback - line 2484, col 22 - rule NAME - Global not defined - b"
	]
}
```

**Review by marsninja — APPROVED** [review]
LGTM!! Nice Work @amadolid

**Pull request merged**
