### PR TITLE
Azure Terraform Script

### PR DESCRIPTION
**Pull request by itsbharatsaini**
Adding azure terraform init script.

### CODE REVIEW

**Review by ashagraw91 — COMMENTED** [review]
Add README.md file and explain how to run. check my aws one

**Review by marsninja — COMMENTED** [review]
Thanks @itsbharatsaini ! Is this good to merge? @asimsalim mentioned it may be ready and shared a video.

**Comment by asimsalim** [comment]
@marsninja  this is good to merge.

**Review by asimsalim — APPROVED** [review]

**Review by ashagraw91 — APPROVED** [review]
good to go

**Review by marsninja — APPROVED** [review]
LGTM! Thanks @itsbharatsaini

**Pull request merged**
