### PR TITLE
changed jac run to walker run

### PR DESCRIPTION
**Pull request by Shawn-Jemmott**
@ypkang

### CODE REVIEW

**Review by marsninja — APPROVED** [review]
LGTM! Thanks @Shawn-Jemmott

**Comment by marsninja** [comment]
@ypkang Needs conflict resolution

**Comment by ypkang** [comment]
@Shawn-Jemmott I don't think the changes work here. We can't just simply change `jac run` to `walker run` arbitrarily., The places where you are proposing to change, sentinel register hasn't even been introduced yet. `walker run` will not work. Also, `jsserv` is introduced at the end and most people will be running everything locally in jsctl for most of this codelab so they wouldn't really need to worry about sentinel register or walker run.

A better solution here is to add a quick new section at the end, after `jsserv`, explaining that if they are running jaseci on a remote server and wish to train model there, they can do the following (sentinel register, walker run etc.).

**Comment by ypkang** [comment]
@Shawn-Jemmott could you take a look at my comment and make the change here? If anything is not clear, let me know.

**Review by ypkang — CHANGES_REQUESTED** [review]
See comment above.

**Comment by ypkang** [comment]
Gonna close this for now. Not a super important thing to add now and we can come back to it later.

**Pull request closed without merging**
