### PR TITLE
Fixing dependency issues in VC_TTS and remove older version of TTS

### PR DESCRIPTION
**Pull request by TharukaCkasthuri**

### CODE REVIEW

**Comment by TharukaCkasthuri** [comment]
removed older version of TTS.

**Comment by ypkang** [comment]
I am not sure if this PR fixes the issue. I tried on this branch, installing jac_speech then installing jac_nlp. And when I run `actions load module vc_tts` or `actions load module stt`, i get the following
```
{
  "response": "Internal Exception: Numba needs NumPy 1.22 or less",
  "success": false,
  "errors": [
    "Internal Exception: Numba needs NumPy 1.22 or less"
  ],
  "stack_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/jaseci/api/interface.py\", line 192, in general_interface_to_api\n    ret = getattr(_caller, api_name)(**param_map)\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/jaseci/api/actions_api.py\", line 95, in actions_load_module\n    success = lact.load_module_actions(mod)\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/jaseci/actions/live_actions.py\", line 107, in load_module_actions\n    mod = importlib.import_module(mod)\n",
    "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n",
    "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
    "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
    "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
    "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/jac_speech/vc_tts/__init__.py\", line 1, in <module>\n    from .vc_tts import *  # noqa\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/jac_speech/vc_tts/vc_tts.py\", line 4, in <module>\n    from TTS.api import TTS\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/TTS/api.py\", line 4, in <module>\n    from TTS.utils.synthesizer import Synthesizer\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/TTS/utils/synthesizer.py\", line 14, in <module>\n    from TTS.utils.audio import AudioProcessor\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/TTS/utils/audio/__init__.py\", line 1, in <module>\n    from TTS.utils.audio.processor import AudioProcessor\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/TTS/utils/audio/processor.py\", line 3, in <module>\n    import librosa\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/librosa/__init__.py\", line 211, in <module>\n    from . import core\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/librosa/core/__init__.py\", line 5, in <module>\n    from .convert import *  # pylint: disable=wildcard-import\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/librosa/core/convert.py\", line 7, in <module>\n    from . import notation\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/librosa/core/notation.py\", line 8, in <module>\n    from ..util.exceptions import ParameterError\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/librosa/util/__init__.py\", line 83, in <module>\n    from .utils import *  # pylint: disable=wildcard-import\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/librosa/util/utils.py\", line 10, in <module>\n    import numba\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/numba/__init__.py\", line 200, in <module>\n    _ensure_critical_deps()\n",
    "  File \"/home/ypkang/.local/lib/python3.10/site-packages/numba/__init__.py\", line 140, in _ensure_critical_deps\n    raise ImportError(\"Numba needs NumPy 1.22 or less\")\n",
    "ImportError: Numba needs NumPy 1.22 or less\n"
  ]
}
```

**Comment by ypkang** [comment]
@chandralegend

**Review by marsninja — APPROVED** [review]
LGTM! @TharukaCkasthuri 

@ypkang you good to merge this one?

**Comment by marsninja** [comment]
Welp it has conflicts, we'll discuss

**Comment by TharukaCkasthuri** [comment]
Fixing in new PR

**Pull request closed without merging**
