### PR TITLE
[Feat]: Jaseci webhook

### PR DESCRIPTION
**Pull request by panikingginoo12**

### CODE REVIEW

**Comment by asimsalim** [comment]
Won't this break existing implementations of Walker_callback ? @amadolid @panikingginoo12

**Comment by amadolid** [comment]
> Won't this break existing implementations of Walker_callback ? @amadolid @panikingginoo12

ow, it will sir, should retain it for now?

**Comment by asimsalim** [comment]
Better to keep walker_callback and deprecate walker_webhook

**Comment by amadolid** [comment]
> > Won't this break existing implementations of Walker_callback ? @amadolid @panikingginoo12
> 
> ow, it will sir, should retain it for now?



> Better to keep walker_callback and deprecate walker_webhook

ow wait, walker_webhook is the new name. walker_callback should be the one deprecated

**Comment by asimsalim** [comment]
Yes. My mistake . I meant The other way. Deprecate Walker_callback

**Comment by amadolid** [comment]
walker_webhook removed

**Comment by asimsalim** [comment]
@panikingginoo12 @amadolid  Can you fix the merge conflict and also add the documentation ? the old readme seems to be deleted and I assume the steps are now different.

**Review by marsninja — APPROVED** [review]
Going to pass this for now, Thanks @panikingginoo12 ! Will need docs on webhook

**Pull request merged**
