### PR TITLE
[FEATURE-REQUEST]: Websocket via channels[daphne]

### PR DESCRIPTION
**Pull request by amadolid**
CHANGES:
 - Unit test and docs are included

### CODE REVIEW

**Comment by amadolid** [comment]
image

**Comment by amadolid** [comment]
image

**Comment by amadolid** [comment]
image

**Review by ypkang — COMMENTED** [review]
The PR looks good. I want to manually test this before merging since this changes from wsgi to asgi.

**Review by marsninja — APPROVED** [review]
This LGTM!

**Pull request merged**
