### PR TITLE
Prometheus yaml

### PR DESCRIPTION
**Pull request by Gorgeous-Patrick**
## Describe your changes
I have added a yaml file that can set up a prometheus service for jaseci. The file itself is equivalent to `helm install jaseci-prometheus prometheus-community/prometheus`. 
## Link to related issue
N/A
## Does this introduce new feature or change existing feature of Jaseci? If so, please add tests.
No new features for jaseci core system.
## Will this impact Jaseci users? If so, please write a paragraph describing the impact.
They can automatically deploy jaseci prometheus services.
## Anything in this PR should the Jaseci developer/contributor community pay particular attention to? If so, please describe.
N/A

### CODE REVIEW

**Comment by ypkang** [comment]
@Gorgeous-Patrick to add a quick readme with steps to access the prometheus interface and an example prometheus query to try to test that the prometheus stack is working properly.

**Comment by marsninja** [comment]
@Gorgeous-Patrick @ypkang Actually lets look at this together. The goal with adding jaseci- in front of prometheus is so we'd have a certain kind of isolation of multiple "full jaseci stacks" that might coexist. There are some assumptions to this that may need to be checked (such that 2 full prometheus stacks can be isolated and run in the same cluster). Ultimately this is a preparatory step to JSORC spooling out jaseci resources. My plan is for a given Jaseci instance, the JSORC inside of it would create k8s resources and append a jaseci instance ID to each resource created for isolation. We'll talk more. Looking forward to it!

**Comment by Gorgeous-Patrick** [comment]
> @Gorgeous-Patrick @ypkang Actually lets look at this together. The goal with adding jaseci- in front of prometheus is so we'd have a certain kind of isolation of multiple "full jaseci stacks" that might coexist. 

Are you talking about Kubernetes namespace? I think that the common practice here is that you can create a namespace called jaseci and put everything in to it (including jaseci core services themselves).

@marsninja

**Comment by ypkang** [comment]
@Gorgeous-Patrick can you create a new folder under `scripts` called `scripts/js-prometheus` and put the readme and yaml files under it?

**Comment by Gorgeous-Patrick** [comment]
folder created. Ready for another review @ypkang

**Review by ypkang — APPROVED** [review]

**Pull request merged**
