### PR TITLE
flair_ner val and test improvement and jac build tutorial

### PR DESCRIPTION
**Pull request by SatyamRajawat**

### CODE REVIEW

**Comment by ypkang** [comment]
@AshishMahendra Review (if you haven't), approve and merge this if the code changes look good. We will do another iteration on the tutorial after we are done with a good version of the biencoder tutorial.

**Review by AshishMahendra — APPROVED** [review]
LGTM

**Review by AshishMahendra — APPROVED** [review]

**Comment by ypkang** [comment]
@ypkang to review and merge.

**Comment by ypkang** [comment]
This looks pretty good. I might do another pass soon and fix some wording and writings but this is a very good version to put in.,=

**Review by ypkang — APPROVED** [review]

**Pull request merged**
