### PR TITLE
[REFACTOR]: Spawn Call 

### PR DESCRIPTION
**Pull request by amadolid**
PREVIOUS BEHAVIOR:
`walker generic entry` **=>** `node entries (generic/typed)` **=>** _back to_ `walker typed entry` **=>** `walker typed exit` **=>** _back to_ `node exits (generic/typed)` => _back to_ `walker generic exit`

REFACTORED BEHAVIOR:
`walker generic entry` **=>** `walker typed entry` **=>** `node generic entry` **=>** `node typed entry` **=>** `node typed exit` **=>** `node generic exit` **=>** _back to_ `walker typed exit` **=>** `walker generic exit`

In this approach, we limit the back and forth of execution to `walker -> node -> walker`. It can also make the execution more "declarative".

It's also more direct if we plan in future to support the `with entry` and `with exit` approach

### CODE REVIEW

**Comment by amadolid** [comment]
REBASED

**Comment by ChrisIsKing** [comment]
@amadolid Actually should there be a difference between generic vs typed order? I'm thinking that order of declaration should take preference in this case. Thoughts @ypkang ?

**Comment by ChrisIsKing** [comment]
Or by generic entry/exit do you mean standard `can on_entry with entry {}` / `can on_exit with exit {}`

**Comment by amadolid** [comment]
> Or by generic entry/exit do you mean standard `can on_entry with entry {}` / `can on_exit with exit {}`

yup, abilities that doesn't have target type
In my perspective, it should be prioritize as it technically more `open` than with type checking.

**Comment by amadolid** [comment]
REBASED

**Comment by amadolid** [comment]
REBASED

**Comment by ChrisIsKing** [comment]
@marsninja Any reservations about this revision?

**Review by ChrisIsKing — APPROVED** [review]

**Comment by ypkang** [comment]
@amadolid can you resolve the conflict on this? I am okay with merging this.

**Comment by amadolid** [comment]
Moved to https://github.com/Jaseci-Labs/jaseci/pull/1447
PR#1447 is minimal. Additional changes from PR#1354 can be added on different PR once PR#1447 is merged

**Pull request closed without merging**
