### PR TITLE
Add: JPrime.jac as an example.

### PR DESCRIPTION
**Pull request by Gorgeous-Patrick**
A minimal viable version of JPrime is added.

### CODE REVIEW

**Comment by ypkang** [comment]
BTW I converted this to draft for now since it is still work in progress

**Comment by Gorgeous-Patrick** [comment]
ohh okay then

**Comment by Gorgeous-Patrick** [comment]
I have improved the JPrime.. It now has a walker that answers the questions given entities or intents. Also, the system passes the list of nodes using walker arguments, not storing it everywhere it in every node. 

Still working on the tests

**Comment by ypkang** [comment]
@Gorgeous-Patrick This is a great starting point for the program so I am going to merge this as is and you can open up a new PR for the tests and AI changes we talked about today.

**Review by ypkang — APPROVED** [review]

**Pull request merged**
