### PR TITLE
[LOCAL-DB]: Initial Implementation

### PR DESCRIPTION
**Pull request by amadolid**
Unit tests should now work without DB. However, github tests should still run it on proper DB

### CODE REVIEW

**Comment by amadolid** [comment]
REBASED

**Review by ypkang — COMMENTED** [review]
This looks great! I love that it removes jac-mini and all the code around it..

Question @amadolid  -- are there any known limitations with montyDB?

**Comment by amadolid** [comment]
> This looks great! I love that it removes jac-mini and all the code around it..
> 
> Question @amadolid -- are there any known limitations with montyDB?

Yes, the transactional approach is currently mocked.
Indexing also doesn't work

**Comment by amadolid** [comment]
> This looks great! I love that it removes jac-mini and all the code around it..
> 
> Question @amadolid -- are there any known limitations with montyDB?

Yes, the transactional approach and indexing are currently mocked.

**Comment by amadolid** [comment]
REBASED

**Review by ypkang — APPROVED** [review]
LGTM.

**Pull request merged**
