### PR TITLE
Clean Soical auth setup

### PR DESCRIPTION
**Pull request by pathakshyam**

### CODE REVIEW

**Comment by marsninja** [comment]
Is this one ready for review @pathakshyam or @asimsalim ?

**Comment by asimsalim** [comment]
> Is this one ready for review @pathakshyam or @asimsalim ?

Hi Jason .. This is ready for review

**Comment by ypkang** [comment]
Looks like this one has been ready for review. @pathakshyam could you resolve the conflicts real quick? And convert it back from draft PR once you have resolved the conflict.

**Comment by amadolid** [comment]
moved to https://github.com/Jaseci-Labs/jaseci/pull/686

**Pull request closed without merging**
