### PR TITLE
Batch Cosine SImilarity

### PR DESCRIPTION
**Pull request by chandralegend**
## Describe your changes
Batch Cosine Similarity where you can give a two 2D or 1D vectors to calculate cosine similarity

### CODE REVIEW

**Comment by chandralegend** [comment]
@ypkang

**Review by marsninja — CHANGES_REQUESTED** [review]
@chandralegend This looks like a nice change! 

@ypkang Lets ensure there is a simple test and some documentation changes that go with this change, should be findable off of the main Readme (as per the new mdbooks guidelines)

**Comment by ypkang** [comment]
@chandralegend could you add a test for this? you can create a new file and jac fixture in here https://github.com/Jaseci-Labs/jaseci/tree/main/jaseci_core/jaseci/actions/standard/tests

**Review by ypkang — APPROVED** [review]
LGTM

**Comment by chandralegend** [comment]
> LGTM

@marsninja

**Review by ypkang — APPROVED** [review]

**Pull request merged**
